language: python

python:
  - 2.7

services: postgresql

addons:
  postgresql: "9.6"

notifications:
  slack:
    secure: u16lrO0tlSZkEYP9ofqVOdmM6CRFrjDnp8Dauk71wLx9ko1se6v2Gyy4jp+dkPSa2fNnIqzt29l1oERj0wPX+nz5A2OLnEstvtjYjPgu+VKMhKV7NCz9mLDGe0m0LnV3GGZvD4EZm9FCpfn7biDXIIfZSDAOX3HFh8OGmadNyNVyM0LwJLrVEDOQlN0UiwnWG8+FpQd4Yj1DTjTThhn902v02vQkkTXtog56+4Q0l9SyRFgxg6MQB7xm6+Do4T/As9Cng/ZOp5i/yyYUZUs9WJUMMGD/J2Ye5BxQ5Yg6gEdZP2WtAhOZ7l3mLrsHcGZY8T8A3rdMuVaMpiD+jpRbp9Qx7r8y5nqCwuhjmVuA9Mgl0SLXtW7cbYXqz8ZNVXaRsjfvLyVqGb9vQ4Ia+1vFQQmoDG6cydTO+y0HqvMbJHOk+km+qhQxaBxiJPr+VeD47DBz7KY4A0tPFTvAhJRgNLhe068Ox/l03X5FJ+nECGp5VtS4W643P4hefS3eGyp6ULlWchZnfMqpHjepojvvhJw1IA3/3pQ2x3+2SvOWXOw34yHu4E+LVr7h39ZfShwpITlVIv1Ezap822HDj06wS1uUuGkAu29wlSMfX0qrDWF3KzGOV+fugpAaW+wnvgjHWIrh/Q8aM9H3DXk2nd2hRgUSyoaAxbMuLOPPgCPWT6c=

env:
  - DATABASE_URL=postgres://postgres:@localhost/travisci

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - python manage.py migrate --noinput
  - python manage.py collectstatic

script:
  - python manage.py test
